---
- hosts: localhost
  connection: local
  become: true

  tasks:

# Remove packages
  - name: Remove any residual docker packages
    apt:
      state: absent
      name:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc


# Adding Repo Keys
  - name: add Enpass key for repo
    apt_key:
      url: "https://apt.enpass.io/keys/enpass-linux.key"
      state: present
  - name: add Vivaldi key for repo
    apt_key:
      url: "https://repo.vivaldi.com/archive/linux_signing_key.pub"
      state: present
  - name: add VSCode key for repo
    apt_key:
      url: "https://packages.microsoft.com/keys/microsoft.asc"
      state: present


# Adding Repos
  - name: Add Enpass repository into sources list
    apt_repository:
      repo: deb https://apt.enpass.io/ stable main
      state: present
      update_cache: yes
  - name: Add Vivaldi repository into sources list
    apt_repository:
      repo: deb https://repo.vivaldi.com/archive/deb/ stable main
      state: present
      update_cache: yes
  - name: Add VSCode repository into sources list
    apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
      state: present
      update_cache: yes


# Refresh Apt Cache
#  - name: Update apt cache
#    apt:
#      update_cache: yes

# Installing Packages
  - name: isntall packages
    package: 
      name:
        - htop
        - gnome-tweak-tool
        - bpytop
        - enpass
        - vivaldi-stable
        - code
        - profile-sync-daemon
        - gnome-boxes


# Copying over config files
  - name: Copy Profile Sync Daemon conf file
    copy:
      src: files/psd.conf
      dest: /home/cyberfighter/.config/psd/psd.conf
      owner: cyberfighter
      group: cyberfighter

# Systemd services
  - name: Start Profile Sync Daemon
    systemd:
      name: psd
      state: started
      enabled: yes

####### Examples ########

#  - name: copy wallpaper file
#    copy:
#      src: files/wallpaper.png
#      dest: /usr/share/backgrounds/ansible-wallpaper.png
#      owner: root
#      group: root
#  - name: set wallpaper
#    become_user: cyberfighter	
#    dconf:
#      key: "/org/gnome/desktop/background/picture-uri"
#      value: "'file://///usr/share/backgrounds/ansible-wallpaper.png'"

#  - name: set wallpaper position
#    become_user: cyberfighter
#    dconf:
#      key: "/org/gnome/desktop/background/picture-options"
#      value: "'zoom'"
