---
- hosts: localhost
  connection: local
  become: true

  tasks:

# Mount all drives
# Install CFIS Prereqs
  - name: Install CFIS Prereqs
    package: 
      name:
        - cifs-utils
  - name: Mount Scanner Network Drives
    mount:
      src: //synlgy-ds918.cyberfighter.space/scanner
      path: /mnt/NAS_Scanner
      opts: credentials=/home/cyberfighter/.nas_Jonny_credentials,iocharset=utf8,uid=1028,gid=100,noperm,vers=2.0
      state: mounted
      fstype: cifs
  - name: Mount Jonny Network Drives
    mount:
      src: //synlgy-ds918.cyberfighter.space/home
      path: /mnt/NAS_Jonny
      opts: credentials=/home/cyberfighter/.nas_Jonny_credentials,iocharset=utf8,uid=1028,gid=100,noperm,vers=2.0
      state: mounted
      fstype: cifs
  - name: Mount Temp Network Drives
    mount:
      src: //synlgy-ds918.cyberfighter.space/Temp
      path: /mnt/NAS_Temp
      opts: credentials=/home/cyberfighter/.nas_Jonny_credentials,iocharset=utf8,uid=1028,gid=100,noperm,vers=2.0
      state: mounted
      fstype: cifs
  - name: Mount Media Network Drives
    mount:
      src: //synlgy-ds918.cyberfighter.space/Media
      path: /mnt/NAS_Media
      opts: credentials=/home/cyberfighter/.nas_Jonny_credentials,iocharset=utf8,uid=1028,gid=100,noperm,vers=2.0
      state: mounted
      fstype: cifs

# Remove packages
  - name: Remove any residual docker packages
    apt:
      state: absent
      name:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc

# Install Docker Prereqs
  - name: Install Docker Prereqs
    package: 
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

# Adding Repo Keys
  - name: add Enpass key for repo
    apt_key:
      url: "https://apt.enpass.io/keys/enpass-linux.key"
      state: present
  - name: add Vivaldi key for repo
    apt_key:
      url: "https://repo.vivaldi.com/archive/linux_signing_key.pub"
      state: present
  - name: add VSCode key for repo
    apt_key:
      url: "https://packages.microsoft.com/keys/microsoft.asc"
      state: present
  - name: add Docker key for repo
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present



# Adding Repos
  - name: Add Enpass repository into sources list
    apt_repository:
      repo: deb https://apt.enpass.io/ stable main
      state: present
      update_cache: yes
  - name: Add Vivaldi repository into sources list
    apt_repository:
      repo: deb https://repo.vivaldi.com/archive/deb/ stable main
      state: present
      update_cache: yes
  - name: Add VSCode repository into sources list
    apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
      state: present
      update_cache: yes
  - name: Add Docker repository into sources list
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
      state: present
      update_cache: yes
  


# Refresh Apt Cache
#  - name: Update apt cache
#    apt:
#      update_cache: yes

# Installing Packages
  - name: Install packages
    package: 
      name:
        - htop
        - gnome-tweak-tool
        - enpass
        - vivaldi-stable
        - code
        - profile-sync-daemon
        - gnome-boxes
        - python3-pip
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - micro
        - chromium

# Install Flatpaks
  - name: Install Flatpaks
    flatpak:
        name: org.videolan.VLC
        state: present
        method: user

# Install Pip Packages
  - name: Install Pip Packages
    pip:
      name: bpytop


# Copying over config files
  - name: Copy Profile Sync Daemon conf file
    copy:
      src: files/psd.conf
      dest: /home/cyberfighter/.config/psd/psd.conf
      owner: cyberfighter
      group: cyberfighter


# Systemd services
  - name: Start Profile Sync Daemon
    become_user: cyberfighter
    systemd:
      name: psd
      scope: user
      state: started
      enabled: yes

# Set User Settings
  # Set Wallpaper
  - name: copy wallpaper file
    copy:
      src: files/ansible-flying-spaceship-wallpaper.jpg
      dest: /usr/share/backgrounds/ansible-flying-spaceship-wallpaper.jpg
      owner: root
      group: root
  - name: set wallpaper
    become_user: cyberfighter
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file://///usr/share/backgrounds/ansible-flying-spaceship-wallpaper.jpg'"
  - name: set wallpaper position
    become_user: cyberfighter
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
  # Gnome Tweaks
  - name: Apply Gnome Tweaks Button Layout
    become_user: cyberfighter
    dconf:
      key: "/org/gnome/desktop/wm/preferences/button-layout"
      value: "'appmenu:minimize,maximize,close'"
  - name: Apply Gnome Tweaks Battery Percentage
    become_user: cyberfighter
    dconf:
      key: "/org/gnome/desktop/interface/show-battery-percentage"
      value: "true"
  - name: Apply Gnome Tweaks Show Weekday
    become_user: cyberfighter
    dconf:
      key: "/org/gnome/desktop/interface/clock-show-weekday"
      value: "true"